### ISSUE TITLE
License missing?

### ISSUE THREAD

**Issue by dl3jop** [pcabreracamara/QTrigdoppler#1]
Hey, I want to do a fork with some changes and additions. Under which license are you sharing the code?

**Comment by pcabreracamara** [comment]
Hi Joshua,

Yes, you're right, I forgot to upload the license. The project it's shared under GPL v3 license.

Kind regards,
Pedro

**Comment by pcabreracamara** [comment]
Included GPL v3 license in "COPYING" file. Thank you Joshua
